### PR TITLE
Use array for tito releaser args

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
This will allow defining as in https://github.com/theforeman/foreman-packaging/pull/2235#issuecomment-369299400

**Comment by ekohl** [comment]
How does this deal with strings? In python calling join on a string leads to ... interesting results.

**Comment by ehelms** [comment]
I don't know actually. If a user passes a string, then this will likely error and thats on the user. Same would be true of any parameter that was improperly sent through in Ansible I think.

**Comment by evgeni** [comment]
I could not find any users of this at the moment, so I am fine with "breaking" it.

@ekohl OK for ya?

**Pull request merged**
