### PR TITLE
Use Ansible 2.5 tests

### PR DESCRIPTION
**Pull request by ekohl**
https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_2.5.html#jinja-tests-used-as-filters

### CODE REVIEW

**Comment by evgeni** [comment]
is that breaking compat with ansible 2.4 and older?

**Comment by ekohl** [comment]
I can change `install_requires` to `ansible >= 2.5`. That's probably the best way.

**Comment by ekohl** [comment]
Updated with the `install_requires` bump.

**Comment by evgeni** [comment]
Aye. So I must admit I dislike to force our users to have "the latest" ansible. How about we wait till 2.6 is released and then merge this?

**Comment by ekohl** [comment]
Given obal is not used by a lot of people and 2.5 is in all current RH-based distros I'm leaning to forcing here. I guess we could look at disabling deprecations but that would hide them until it's too late as well.

**Comment by evgeni** [comment]
ok, let's see what that breaks :D

**Pull request merged**
