### PR TITLE
Cleaning the Dockerfile to remove some layers

### PR DESCRIPTION
**Pull request by Odilhao**

### CODE REVIEW

**Comment by evgeni** [comment]
This seems to have unnecessary changes (actually reverting things we committed today)

**Comment by Odilhao** [comment]
I had to do this changes to speed the container creation locally, will this revert the git-annex change? :thinking:

**Comment by evgeni** [comment]
Interesting, now the diff renders correctly.

**Comment by Odilhao** [comment]
Rebased against the latest commit on master, I don't know why the diff showed like that

**Review by ehelms — APPROVED** [review]

**Comment by evgeni** [comment]
(the fact that this is necessary underlines my disliking of the containerfile syntax, but oh well, here we are.

**Pull request merged**
