### PR TITLE
Add optional branch and commit to update

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
@evgeni Any advice from your experience on how to get the help text formatted properly so that the tests pass? I spent a day tweaking line after line to still fail.

**Comment by evgeni** [comment]
@ehelms delete the help fixture file, it will be recreated with the correct contents ;)

**Comment by ehelms** [comment]
Thanks @evgeni got the help text fixed, now gotta figure out why master is failing with this same error (https://travis-ci.org/github/theforeman/obal/jobs/699295432)

**Comment by evgeni** [comment]
@ehelms I think the tests should be fixed by https://github.com/theforeman/obal/pull/259 -- when that's merged, we should see this green too

**Comment by ehelms** [comment]
Thanks for fixing the tests @evgeni !

**Comment by evgeni** [comment]
This will also require changes to robotello-ci.

**Comment by ehelms** [comment]
PRs opened for both

**Pull request merged**
