### PR TITLE
match action and playbook names

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
Well, technically speaking they already are, in `data` ;)

@ehelms would you like to see a `data/playbooks` next to `data/roles`? (this would require adjusting `role_path` in `ansible.cfg`, though.

**Comment by ehelms** [comment]
Sure, that extra bit would be nice to make it more obvious but if it complicates things I am fine with them where they live today.

**Comment by evgeni** [comment]
@ekohl like https://github.com/theforeman/obal/issues/82?

**Comment by ekohl** [comment]
@evgeni exactly. I saw it after I commented

**Pull request merged**
