### PR TITLE
Fix ansible-lint errors

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
This fails due to newer, Python 3 specific pylint errors:

```
R: 11, 8: Consider using Python 3 style super() without arguments (super-with-arguments)
W: 23, 8: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
```

@evgeni How do I address Python 3 pylint errors without then breaking python 2 pylint?

**Comment by ekohl** [comment]
I think right now you need to disable those lint rules. They're for Python 3-only code bases.

**Comment by evgeni** [comment]
> I think right now you need to disable those lint rules. They're for Python 3-only code bases.

what he said.

**Comment by ehelms** [comment]
I can't figure out how to disable them for Python 3 *only*. If I disable them the way we do elsewhere in the code pylint on Python 2 barfs with an unknown rule.

**Review by evgeni — APPROVED** [review]

**Pull request merged**
